// events
export const README_FETCH_SUCCEEDED = 'README_FETCH_SUCCEEDED'
export const README_FETCH_FAILED = 'README_FETCH_FAILED'
export const MARKDOWN_RETRY_CLICKED = 'MARKDOWN_RETRY_CLICKED'
export const REPO_LOAD_CLICKED = 'REPO_LOAD_CLICKED'
export const ADD_REPO_INPUT_SUBMITTED = 'ADD_REPO_INPUT_SUBMITTED'
export const MARKDOWN_FETCH_STARTED = 'MARKDOWN_FETCH_STARTED'
export const REPO_ADDED = 'REPO_ADDED'

// commands
export const FETCH_MARKDOWN = 'FETCH_MARKDOWN'
export const ADD_REPO = 'ADD_REPO'
